# ============================================================================
# LinkOS — Fallback / Safe-mode UEFI boot entry
# ============================================================================

title    🛠️ LinkOS Safe Mode (%ARCH%, UEFI, fallback initramfs)
sort-key 03
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/intel-ucode.img
initrd   /%INSTALL_DIR%/boot/amd-ucode.img
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-fallback.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=4G
