# ============================================================================
# LinkOS — LightDM GTK Greeter configuration
# Fluent Dark theme for the login screen.
# ============================================================================

[greeter]
theme-name = Fluent-Dark
icon-theme-name = Fluent-Dark
font-name = Cascadia Code 11
background = /usr/share/backgrounds/linkos/linkos-wallpaper.jpg
user-background = false
show-language-selector = true
show-session-selector = true
show-power = true
show-clock = true
clock-format = %a, %d %b %H:%M
position = 50%,center 50%,center
default-user-image = #linkos-user
hide-user-image = false
round-user-image = true
show-a11y = true

[activation-delay]
delay = 0
