# ============================================================================
# LinkOS — Calamares fstab module
# Generates /etc/fstab on the target system.
# ============================================================================

# Use partitions' UUIDs (more stable than labels)
mountOptions:
  default: defaults,noatime
  btrfs: defaults,noatime,compress=zstd:1,space_cache,subvol=%subvol%
  ext4: defaults,noatime
  xfs: defaults,noatime
  f2fs: defaults,noatime
  vfat: defaults,utf8

# Use UUIDs in /etc/fstab
mountType:
  default: uuid

# Generate entries for swap
swap: true
