# ============================================================================
# LinkOS — Calamares luksopenswaphook module
# ============================================================================

# Path to the crypttab file
fileName: /etc/crypttab

# Name of the swap LUKS device
swapDeviceName: swap_crypt
