# ============================================================================
# LinkOS — Calamares mount module
# ============================================================================

# Where to mount the new root during install
mountPoint: /mnt

# Extra mount options
extraMounts:
  - device: proc
    fs: proc
    mountPoint: /proc
  - device: sys
    fs: sysfs
    mountPoint: /sys
  - device: /dev
    fs: none
    mountPoint: /dev
    options: bind
  - device: /dev/pts
    fs: devpts
    mountPoint: /dev/pts
  - device: shm
    fs: tmpfs
    mountPoint: /dev/shm
  - device: /run
    fs: none
    mountPoint: /run
    options: bind

extraMountsEfi:
  - device: efivarfs
    fs: efivarfs
    mountPoint: /sys/firmware/efi/efivars
