# ============================================================================
# LinkOS — Calamares preservefiles module
# Preserves files from the live system to the installed system.
# ============================================================================

files:
  - from: /etc/machine-id
    to: /etc/machine-id
  - from: /var/lib/NetworkManager/secret_key
    to: /var/lib/NetworkManager/secret_key

perm: root:root:0600
